<?php

namespace App\Http\Controllers;

abstract class Controller
{
    // This abstract base class mirrors the structure generated by Laravel's
    // default controller stub. Keeping it in place allows future controllers
    // to inherit shared helpers (authorization, middleware, etc.) without
    // needing to refactor existing classes once the application grows.
}
